#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include "ds_battery_enhancement.hpp"
#include "ds_bms_middleware_v2.hpp"
#include "torque_enhancement.hpp"

namespace py = pybind11;

PYBIND11_MODULE(ds_enhancer_pybind, m) {
    m.doc() = "pybind11 Python bindings for DS EV Battery Enhancement Software Core";

    // ========================================================================
    // Core DS Structs & Classes
    // ========================================================================

    py::class_<ds::DSConfig>(m, "DSConfig")
        .def(py::init<>())
        .def_readwrite("enable_feen_battery_integration", &ds::DSConfig::enable_feen_battery_integration)
        .def_readwrite("lambda", &ds::DSConfig::lambda)
        .def_readwrite("tau_min", &ds::DSConfig::tau_min)
        .def_readwrite("phi_decay_rate", &ds::DSConfig::phi_decay_rate)
        .def_readwrite("thermodynamic_beta", &ds::DSConfig::thermodynamic_beta)
        .def_readwrite("entropy_weight", &ds::DSConfig::entropy_weight)
        .def_readwrite("nominal_capacity_ah", &ds::DSConfig::nominal_capacity_ah)
        .def_readwrite("nominal_voltage", &ds::DSConfig::nominal_voltage)
        .def_readwrite("max_temperature", &ds::DSConfig::max_temperature)
        .def_readwrite("min_temperature", &ds::DSConfig::min_temperature)
        .def_readwrite("max_current", &ds::DSConfig::max_current)
        .def_readwrite("energy_conservation_tolerance", &ds::DSConfig::energy_conservation_tolerance)
        .def("validate", &ds::DSConfig::validate);

    py::class_<ds::HealthPrediction>(m, "HealthPrediction")
        .def(py::init<>())
        .def_readwrite("remaining_capacity_percent", &ds::HealthPrediction::remaining_capacity_percent)
        .def_readwrite("cycles_to_80_percent", &ds::HealthPrediction::cycles_to_80_percent)
        .def_readwrite("estimated_eol_cycles", &ds::HealthPrediction::estimated_eol_cycles)
        .def_readwrite("confidence", &ds::HealthPrediction::confidence)
        .def_readwrite("warning_triggered", &ds::HealthPrediction::warning_triggered)
        .def_readwrite("degradation_rate", &ds::HealthPrediction::degradation_rate)
        .def_readwrite("time_to_80_percent_years", &ds::HealthPrediction::time_to_80_percent_years);

    py::class_<ds::OptimalChargingProfile>(m, "OptimalChargingProfile")
        .def(py::init<>())
        .def_readwrite("recommended_current_limit", &ds::OptimalChargingProfile::recommended_current_limit)
        .def_readwrite("recommended_voltage_limit", &ds::OptimalChargingProfile::recommended_voltage_limit)
        .def_readwrite("recommended_temperature", &ds::OptimalChargingProfile::recommended_temperature)
        .def_readwrite("estimated_charge_time", &ds::OptimalChargingProfile::estimated_charge_time)
        .def_readwrite("degradation_impact", &ds::OptimalChargingProfile::degradation_impact)
        .def_readwrite("max_safe_current", &ds::OptimalChargingProfile::max_safe_current)
        .def_readwrite("max_safe_voltage", &ds::OptimalChargingProfile::max_safe_voltage);

    py::class_<ds::DSState>(m, "DSState")
        .def(py::init<>())
        .def_readwrite("voltage", &ds::DSState::voltage)
        .def_readwrite("current", &ds::DSState::current)
        .def_readwrite("temperature", &ds::DSState::temperature)
        .def_readwrite("state_of_charge", &ds::DSState::state_of_charge)
        .def_readwrite("entropy", &ds::DSState::entropy)
        .def_readwrite("cycle_count", &ds::DSState::cycle_count)
        .def_readwrite("degradation", &ds::DSState::degradation)
        .def_readwrite("phi_magnitude", &ds::DSState::phi_magnitude)
        .def_readwrite("lambda", &ds::DSState::lambda)
        .def_readwrite("grad_phi", &ds::DSState::grad_phi)
        .def_readwrite("energy_psi", &ds::DSState::energy_psi)
        .def_readwrite("energy_phi", &ds::DSState::energy_phi)
        .def_readwrite("energy_metric", &ds::DSState::energy_metric)
        .def_readwrite("energy_total", &ds::DSState::energy_total);

    py::class_<ds::EnhancedState>(m, "EnhancedState")
        .def(py::init<>())
        .def_readwrite("feen_trust_metric", &ds::EnhancedState::feen_trust_metric)
        .def_readwrite("state", &ds::EnhancedState::state)
        .def_readwrite("health", &ds::EnhancedState::health)
        .def_readwrite("charging", &ds::EnhancedState::charging)
        .def_readwrite("degradation_warning", &ds::EnhancedState::degradation_warning)
        .def_readwrite("ds_confidence", &ds::EnhancedState::ds_confidence)
        .def_readwrite("input_clamped", &ds::EnhancedState::input_clamped)
        .def_readwrite("energy_conservation_error", &ds::EnhancedState::energy_conservation_error)
        .def_readwrite("numerical_stability", &ds::EnhancedState::numerical_stability);

    // ========================================================================
    // Middleware Structs & Classes
    // ========================================================================

    py::class_<ds_plugin::DiagnosticReport>(m, "DiagnosticReport")
        .def(py::init<>())
        .def_readwrite("pack_soh_percent", &ds_plugin::DiagnosticReport::pack_soh_percent)
        .def_readwrite("pack_soc_percent", &ds_plugin::DiagnosticReport::pack_soc_percent)
        .def_readwrite("estimated_range_km", &ds_plugin::DiagnosticReport::estimated_range_km)
        .def_readwrite("cycles_to_eol", &ds_plugin::DiagnosticReport::cycles_to_eol)
        .def_readwrite("pack_health_percent", &ds_plugin::DiagnosticReport::pack_health_percent)
        .def_readwrite("estimated_remaining_cycles", &ds_plugin::DiagnosticReport::estimated_remaining_cycles)
        .def_readwrite("total_cells", &ds_plugin::DiagnosticReport::total_cells)
        .def_readwrite("weak_cell_count", &ds_plugin::DiagnosticReport::weak_cell_count)
        .def_readwrite("weak_cell_ids", &ds_plugin::DiagnosticReport::weak_cell_ids)
        .def_readwrite("min_cell_voltage", &ds_plugin::DiagnosticReport::min_cell_voltage)
        .def_readwrite("max_cell_voltage", &ds_plugin::DiagnosticReport::max_cell_voltage)
        .def_readwrite("voltage_imbalance_mv", &ds_plugin::DiagnosticReport::voltage_imbalance_mv)
        .def_readwrite("average_cell_temp_c", &ds_plugin::DiagnosticReport::average_cell_temp_c)
        .def_readwrite("max_cell_temp_c", &ds_plugin::DiagnosticReport::max_cell_temp_c)
        .def_readwrite("min_cell_temp_c", &ds_plugin::DiagnosticReport::min_cell_temp_c)
        .def_readwrite("ds_metric_trace", &ds_plugin::DiagnosticReport::ds_metric_trace)
        .def_readwrite("ds_entropy", &ds_plugin::DiagnosticReport::ds_entropy)
        .def_readwrite("ds_phi_magnitude", &ds_plugin::DiagnosticReport::ds_phi_magnitude)
        .def_readwrite("ds_confidence", &ds_plugin::DiagnosticReport::ds_confidence)
        .def_readwrite("weak_cell_warning", &ds_plugin::DiagnosticReport::weak_cell_warning)
        .def_readwrite("thermal_warning", &ds_plugin::DiagnosticReport::thermal_warning)
        .def_readwrite("voltage_warning", &ds_plugin::DiagnosticReport::voltage_warning)
        .def_readwrite("degradation_warning", &ds_plugin::DiagnosticReport::degradation_warning)
        .def_readwrite("balancing_required", &ds_plugin::DiagnosticReport::balancing_required)
        .def_readwrite("safety_fault", &ds_plugin::DiagnosticReport::safety_fault)
        .def_readwrite("soc_warning", &ds_plugin::DiagnosticReport::soc_warning)
        .def_readwrite("low_temp_warning", &ds_plugin::DiagnosticReport::low_temp_warning)
        .def_readwrite("instantaneous_power_kw", &ds_plugin::DiagnosticReport::instantaneous_power_kw)
        .def_readwrite("average_efficiency", &ds_plugin::DiagnosticReport::average_efficiency)
        .def_readwrite("energy_throughput_kwh", &ds_plugin::DiagnosticReport::energy_throughput_kwh)
        .def_readwrite("last_update_time_ms", &ds_plugin::DiagnosticReport::last_update_time_ms)
        .def_readwrite("average_update_time_ms", &ds_plugin::DiagnosticReport::average_update_time_ms)
        .def_readwrite("degradation_rate_per_cycle", &ds_plugin::DiagnosticReport::degradation_rate_per_cycle)
        .def_readwrite("metric_trace", &ds_plugin::DiagnosticReport::metric_trace)
        .def_readwrite("phi_magnitude", &ds_plugin::DiagnosticReport::phi_magnitude)
        .def_readwrite("entropy_level", &ds_plugin::DiagnosticReport::entropy_level)
        .def_readwrite("time_since_init_s", &ds_plugin::DiagnosticReport::time_since_init_s)
        .def_readwrite("update_count", &ds_plugin::DiagnosticReport::update_count);

    py::class_<ds_plugin::SafetyLimits>(m, "SafetyLimits")
        .def(py::init<>())
        .def_readwrite("min_cell_voltage", &ds_plugin::SafetyLimits::min_cell_voltage)
        .def_readwrite("max_cell_voltage", &ds_plugin::SafetyLimits::max_cell_voltage)
        .def_readwrite("min_pack_voltage", &ds_plugin::SafetyLimits::min_pack_voltage)
        .def_readwrite("max_pack_voltage", &ds_plugin::SafetyLimits::max_pack_voltage)
        .def_readwrite("max_discharge_current", &ds_plugin::SafetyLimits::max_discharge_current)
        .def_readwrite("max_charge_current", &ds_plugin::SafetyLimits::max_charge_current)
        .def_readwrite("min_operating_temp", &ds_plugin::SafetyLimits::min_operating_temp)
        .def_readwrite("max_operating_temp", &ds_plugin::SafetyLimits::max_operating_temp)
        .def_readwrite("max_cell_temp", &ds_plugin::SafetyLimits::max_cell_temp)
        .def_readwrite("min_soc", &ds_plugin::SafetyLimits::min_soc)
        .def_readwrite("max_soc", &ds_plugin::SafetyLimits::max_soc)
        .def_readwrite("max_voltage_imbalance_mv", &ds_plugin::SafetyLimits::max_voltage_imbalance_mv)
        .def_readwrite("min_health_percent", &ds_plugin::SafetyLimits::min_health_percent);

    py::class_<ds_plugin::MiddlewareConfig> config(m, "MiddlewareConfig");

    py::enum_<ds_plugin::MiddlewareConfig::Mode>(config, "Mode")
        .value("SIMPLE", ds_plugin::MiddlewareConfig::Mode::SIMPLE)
        .value("SINGLE_BATTERY", ds_plugin::MiddlewareConfig::Mode::SINGLE_BATTERY)
        .value("MULTI_CELL_PACK", ds_plugin::MiddlewareConfig::Mode::MULTI_CELL_PACK)
        .value("ADVANCED_ML", ds_plugin::MiddlewareConfig::Mode::ADVANCED_ML)
        .export_values();

    config.def(py::init<>())
        .def_readwrite("mode", &ds_plugin::MiddlewareConfig::mode)
        .def_readwrite("chemistry", &ds_plugin::MiddlewareConfig::chemistry)
        .def_readwrite("nominal_capacity_ah", &ds_plugin::MiddlewareConfig::nominal_capacity_ah)
        .def_readwrite("nominal_voltage", &ds_plugin::MiddlewareConfig::nominal_voltage)
        .def_readwrite("series_cells", &ds_plugin::MiddlewareConfig::series_cells)
        .def_readwrite("ds_config", &ds_plugin::MiddlewareConfig::ds_config)
        .def_readwrite("enable_kalman_filter", &ds_plugin::MiddlewareConfig::enable_kalman_filter)
        .def_readwrite("enable_ml_hybrid", &ds_plugin::MiddlewareConfig::enable_ml_hybrid)
        .def_readwrite("enable_cell_balancing", &ds_plugin::MiddlewareConfig::enable_cell_balancing)
        .def_readwrite("safety_limits", &ds_plugin::MiddlewareConfig::safety_limits)
        .def_readwrite("enable_safety_monitoring", &ds_plugin::MiddlewareConfig::enable_safety_monitoring)
        .def_readwrite("enable_logging", &ds_plugin::MiddlewareConfig::enable_logging)
        .def_readwrite("logging_interval_s", &ds_plugin::MiddlewareConfig::logging_interval_s);

    py::enum_<ds::advanced::ChemistryType>(m, "ChemistryType")
        .value("LFP", ds::advanced::ChemistryType::LFP)
        .value("NMC", ds::advanced::ChemistryType::NMC)
        .value("NCA", ds::advanced::ChemistryType::NCA)
        .value("LTO", ds::advanced::ChemistryType::LTO)
        .value("CUSTOM", ds::advanced::ChemistryType::CUSTOM)
        .export_values();

    py::class_<ds_plugin::DSBMSMiddleware>(m, "DSBMSMiddleware")
        .def(py::init<>())
        .def("init", &ds_plugin::DSBMSMiddleware::init, py::arg("capacity_ah"), py::arg("voltage_v"))
        .def("init_advanced", &ds_plugin::DSBMSMiddleware::init_advanced, py::arg("cfg"))
        .def("enhance_cycle", &ds_plugin::DSBMSMiddleware::enhance_cycle, py::arg("v"), py::arg("i"), py::arg("t"), py::arg("soc"), py::arg("dt"))
        .def("get_diagnostics", &ds_plugin::DSBMSMiddleware::get_diagnostics)
        .def("get_health_forecast", &ds_plugin::DSBMSMiddleware::get_health_forecast, py::arg("cycles_ahead") = 100.0)
        .def("get_status_summary", &ds_plugin::DSBMSMiddleware::get_status_summary)
        .def("snapshot", &ds_plugin::DSBMSMiddleware::snapshot);

    // ========================================================================
    // Torque Enhancement Module
    // ========================================================================

    py::enum_<ds::drive::DriveMode>(m, "DriveMode")
        .value("ECO", ds::drive::DriveMode::ECO)
        .value("NORMAL", ds::drive::DriveMode::NORMAL)
        .value("SPORT", ds::drive::DriveMode::SPORT)
        .value("CUSTOM", ds::drive::DriveMode::CUSTOM)
        .export_values();

    py::enum_<ds::drive::RegenMode>(m, "RegenMode")
        .value("LOW", ds::drive::RegenMode::LOW)
        .value("MEDIUM", ds::drive::RegenMode::MEDIUM)
        .value("HIGH", ds::drive::RegenMode::HIGH)
        .value("ADAPTIVE", ds::drive::RegenMode::ADAPTIVE)
        .export_values();

    py::class_<ds::drive::MotorConfig>(m, "MotorConfig")
        .def(py::init<>())
        .def_readwrite("peak_torque_nm", &ds::drive::MotorConfig::peak_torque_nm)
        .def_readwrite("continuous_torque_nm", &ds::drive::MotorConfig::continuous_torque_nm)
        .def_readwrite("base_speed_rpm", &ds::drive::MotorConfig::base_speed_rpm)
        .def_readwrite("max_speed_rpm", &ds::drive::MotorConfig::max_speed_rpm)
        .def_readwrite("efficiency_peak_rpm", &ds::drive::MotorConfig::efficiency_peak_rpm)
        .def_readwrite("peak_power_kw", &ds::drive::MotorConfig::peak_power_kw)
        .def_readwrite("continuous_power_kw", &ds::drive::MotorConfig::continuous_power_kw)
        .def_readwrite("max_motor_temp_c", &ds::drive::MotorConfig::max_motor_temp_c)
        .def_readwrite("max_inverter_temp_c", &ds::drive::MotorConfig::max_inverter_temp_c)
        .def_readwrite("thermal_derating_start_c", &ds::drive::MotorConfig::thermal_derating_start_c)
        .def_readwrite("inverter_derating_start_c", &ds::drive::MotorConfig::inverter_derating_start_c)
        .def_readwrite("torque_rise_rate_nm_per_s", &ds::drive::MotorConfig::torque_rise_rate_nm_per_s)
        .def_readwrite("torque_fall_rate_nm_per_s", &ds::drive::MotorConfig::torque_fall_rate_nm_per_s)
        .def_readwrite("peak_efficiency", &ds::drive::MotorConfig::peak_efficiency)
        .def_readwrite("idle_efficiency", &ds::drive::MotorConfig::idle_efficiency);

    py::class_<ds::drive::DrivetrainConfig>(m, "DrivetrainConfig")
        .def(py::init<>())
        .def_readwrite("front_motor", &ds::drive::DrivetrainConfig::front_motor)
        .def_readwrite("rear_motor", &ds::drive::DrivetrainConfig::rear_motor)
        .def_readwrite("has_front_motor", &ds::drive::DrivetrainConfig::has_front_motor)
        .def_readwrite("has_rear_motor", &ds::drive::DrivetrainConfig::has_rear_motor)
        .def_readwrite("final_drive_ratio", &ds::drive::DrivetrainConfig::final_drive_ratio)
        .def_readwrite("wheel_radius_m", &ds::drive::DrivetrainConfig::wheel_radius_m)
        .def_readwrite("vehicle_mass_kg", &ds::drive::DrivetrainConfig::vehicle_mass_kg)
        .def_readwrite("front_weight_dist", &ds::drive::DrivetrainConfig::front_weight_dist)
        .def_readwrite("drag_coefficient", &ds::drive::DrivetrainConfig::drag_coefficient)
        .def_readwrite("frontal_area_m2", &ds::drive::DrivetrainConfig::frontal_area_m2)
        .def_readwrite("rolling_resistance", &ds::drive::DrivetrainConfig::rolling_resistance)
        .def_readwrite("enable_traction_control", &ds::drive::DrivetrainConfig::enable_traction_control)
        .def_readwrite("max_wheel_slip_ratio", &ds::drive::DrivetrainConfig::max_wheel_slip_ratio)
        .def_readwrite("traction_control_gain", &ds::drive::DrivetrainConfig::traction_control_gain);

    py::class_<ds::drive::BatteryConstraints>(m, "BatteryConstraints")
        .def(py::init<>())
        .def_readwrite("max_discharge_power_kw", &ds::drive::BatteryConstraints::max_discharge_power_kw)
        .def_readwrite("max_charge_power_kw", &ds::drive::BatteryConstraints::max_charge_power_kw)
        .def_readwrite("continuous_power_kw", &ds::drive::BatteryConstraints::continuous_power_kw)
        .def_readwrite("temp_optimal_c", &ds::drive::BatteryConstraints::temp_optimal_c)
        .def_readwrite("temp_soft_limit_c", &ds::drive::BatteryConstraints::temp_soft_limit_c)
        .def_readwrite("temp_hard_limit_c", &ds::drive::BatteryConstraints::temp_hard_limit_c)
        .def_readwrite("temp_cold_limit_c", &ds::drive::BatteryConstraints::temp_cold_limit_c)
        .def_readwrite("soc_min_normal", &ds::drive::BatteryConstraints::soc_min_normal)
        .def_readwrite("soc_min_critical", &ds::drive::BatteryConstraints::soc_min_critical)
        .def_readwrite("soc_max_regen", &ds::drive::BatteryConstraints::soc_max_regen)
        .def_readwrite("soc_max_full", &ds::drive::BatteryConstraints::soc_max_full)
        .def_readwrite("voltage_min", &ds::drive::BatteryConstraints::voltage_min)
        .def_readwrite("voltage_nominal", &ds::drive::BatteryConstraints::voltage_nominal)
        .def_readwrite("voltage_max", &ds::drive::BatteryConstraints::voltage_max)
        .def_readwrite("max_discharge_current_a", &ds::drive::BatteryConstraints::max_discharge_current_a)
        .def_readwrite("max_charge_current_a", &ds::drive::BatteryConstraints::max_charge_current_a)
        .def_readwrite("continuous_current_a", &ds::drive::BatteryConstraints::continuous_current_a);

    py::class_<ds::drive::DSTorqueWeights>(m, "DSTorqueWeights")
        .def(py::init<>())
        .def_readwrite("health_influence", &ds::drive::DSTorqueWeights::health_influence)
        .def_readwrite("degradation_influence", &ds::drive::DSTorqueWeights::degradation_influence)
        .def_readwrite("entropy_influence", &ds::drive::DSTorqueWeights::entropy_influence)
        .def_readwrite("metric_stress_influence", &ds::drive::DSTorqueWeights::metric_stress_influence)
        .def_readwrite("eco_power_fraction", &ds::drive::DSTorqueWeights::eco_power_fraction)
        .def_readwrite("normal_power_fraction", &ds::drive::DSTorqueWeights::normal_power_fraction)
        .def_readwrite("sport_power_fraction", &ds::drive::DSTorqueWeights::sport_power_fraction)
        .def_readwrite("min_torque_fraction", &ds::drive::DSTorqueWeights::min_torque_fraction)
        .def_readwrite("max_ds_derate", &ds::drive::DSTorqueWeights::max_ds_derate)
        .def_readwrite("critical_health_threshold", &ds::drive::DSTorqueWeights::critical_health_threshold)
        .def_readwrite("enable_predictive_limiting", &ds::drive::DSTorqueWeights::enable_predictive_limiting)
        .def_readwrite("forecast_horizon_cycles", &ds::drive::DSTorqueWeights::forecast_horizon_cycles)
        .def_readwrite("forecast_safety_margin", &ds::drive::DSTorqueWeights::forecast_safety_margin)
        .def_readwrite("enable_cell_aware_limiting", &ds::drive::DSTorqueWeights::enable_cell_aware_limiting);

    py::class_<ds::drive::TorqueConfig>(m, "TorqueConfig")
        .def(py::init<>())
        .def_readwrite("drivetrain", &ds::drive::TorqueConfig::drivetrain)
        .def_readwrite("battery", &ds::drive::TorqueConfig::battery)
        .def_readwrite("ds_weights", &ds::drive::TorqueConfig::ds_weights)
        .def_readwrite("drive_mode", &ds::drive::TorqueConfig::drive_mode)
        .def_readwrite("regen_mode", &ds::drive::TorqueConfig::regen_mode)
        .def_readwrite("enable_launch_control", &ds::drive::TorqueConfig::enable_launch_control)
        .def_readwrite("enable_overboost", &ds::drive::TorqueConfig::enable_overboost)
        .def_readwrite("overboost_duration_s", &ds::drive::TorqueConfig::overboost_duration_s)
        .def_readwrite("overboost_power_multiplier", &ds::drive::TorqueConfig::overboost_power_multiplier)
        .def_readwrite("enable_thermal_prediction", &ds::drive::TorqueConfig::enable_thermal_prediction)
        .def_readwrite("enable_cell_aware_limiting", &ds::drive::TorqueConfig::enable_cell_aware_limiting)
        .def_readwrite("enable_smooth_transitions", &ds::drive::TorqueConfig::enable_smooth_transitions)
        .def_readwrite("transition_time_constant_s", &ds::drive::TorqueConfig::transition_time_constant_s)
        .def_readwrite("enable_logging", &ds::drive::TorqueConfig::enable_logging)
        .def_readwrite("logging_interval_s", &ds::drive::TorqueConfig::logging_interval_s);

    py::class_<ds::drive::TorqueResult>(m, "TorqueResult")
        .def(py::init<>())
        .def_readwrite("max_drive_torque_nm", &ds::drive::TorqueResult::max_drive_torque_nm)
        .def_readwrite("max_regen_torque_nm", &ds::drive::TorqueResult::max_regen_torque_nm)
        .def_readwrite("front_torque_fraction", &ds::drive::TorqueResult::front_torque_fraction)
        .def_readwrite("rear_torque_fraction", &ds::drive::TorqueResult::rear_torque_fraction)
        .def_readwrite("max_power_kw", &ds::drive::TorqueResult::max_power_kw)
        .def_readwrite("estimated_efficiency", &ds::drive::TorqueResult::estimated_efficiency)
        .def_readwrite("base_motor_scaling", &ds::drive::TorqueResult::base_motor_scaling)
        .def_readwrite("ds_scaling", &ds::drive::TorqueResult::ds_scaling)
        .def_readwrite("thermal_scaling", &ds::drive::TorqueResult::thermal_scaling)
        .def_readwrite("soc_scaling", &ds::drive::TorqueResult::soc_scaling)
        .def_readwrite("health_scaling", &ds::drive::TorqueResult::health_scaling)
        .def_readwrite("cell_balancing_scaling", &ds::drive::TorqueResult::cell_balancing_scaling)
        .def_readwrite("overall_scaling", &ds::drive::TorqueResult::overall_scaling)
        .def_readwrite("health_derate_active", &ds::drive::TorqueResult::health_derate_active)
        .def_readwrite("thermal_derate_active", &ds::drive::TorqueResult::thermal_derate_active)
        .def_readwrite("entropy_derate_active", &ds::drive::TorqueResult::entropy_derate_active)
        .def_readwrite("metric_derate_active", &ds::drive::TorqueResult::metric_derate_active)
        .def_readwrite("soc_derate_active", &ds::drive::TorqueResult::soc_derate_active)
        .def_readwrite("weak_cell_derate_active", &ds::drive::TorqueResult::weak_cell_derate_active)
        .def_readwrite("power_limit_active", &ds::drive::TorqueResult::power_limit_active)
        .def_readwrite("traction_limit_active", &ds::drive::TorqueResult::traction_limit_active)
        .def_readwrite("overboost_active", &ds::drive::TorqueResult::overboost_active)
        .def_readwrite("launch_control_active", &ds::drive::TorqueResult::launch_control_active)
        .def_readwrite("limp_mode_active", &ds::drive::TorqueResult::limp_mode_active)
        .def_readwrite("computation_time_us", &ds::drive::TorqueResult::computation_time_us)
        .def_readwrite("limiting_factor", &ds::drive::TorqueResult::limiting_factor)
        .def_readwrite("confidence_level", &ds::drive::TorqueResult::confidence_level);

    py::class_<ds::drive::TorqueDiagnostics>(m, "TorqueDiagnostics")
        .def(py::init<>())
        .def_readwrite("average_torque_nm", &ds::drive::TorqueDiagnostics::average_torque_nm)
        .def_readwrite("peak_torque_nm", &ds::drive::TorqueDiagnostics::peak_torque_nm)
        .def_readwrite("average_power_kw", &ds::drive::TorqueDiagnostics::average_power_kw)
        .def_readwrite("peak_power_kw", &ds::drive::TorqueDiagnostics::peak_power_kw)
        .def_readwrite("total_energy_kwh", &ds::drive::TorqueDiagnostics::total_energy_kwh)
        .def_readwrite("regen_energy_kwh", &ds::drive::TorqueDiagnostics::regen_energy_kwh)
        .def_readwrite("average_efficiency", &ds::drive::TorqueDiagnostics::average_efficiency)
        .def_readwrite("motor_efficiency", &ds::drive::TorqueDiagnostics::motor_efficiency)
        .def_readwrite("inverter_efficiency", &ds::drive::TorqueDiagnostics::inverter_efficiency)
        .def_readwrite("max_motor_temp_c", &ds::drive::TorqueDiagnostics::max_motor_temp_c)
        .def_readwrite("max_inverter_temp_c", &ds::drive::TorqueDiagnostics::max_inverter_temp_c)
        .def_readwrite("max_battery_temp_c", &ds::drive::TorqueDiagnostics::max_battery_temp_c)
        .def_readwrite("average_ds_scaling", &ds::drive::TorqueDiagnostics::average_ds_scaling)
        .def_readwrite("derate_event_count", &ds::drive::TorqueDiagnostics::derate_event_count)
        .def_readwrite("total_derate_time_s", &ds::drive::TorqueDiagnostics::total_derate_time_s)
        .def_readwrite("update_count", &ds::drive::TorqueDiagnostics::update_count)
        .def_readwrite("total_time_s", &ds::drive::TorqueDiagnostics::total_time_s)
        .def("reset", &ds::drive::TorqueDiagnostics::reset);

    py::class_<ds::drive::DSTorqueManager>(m, "DSTorqueManager")
        .def(py::init<>())
        .def(py::init<const ds::drive::TorqueConfig&>(), py::arg("config"))
        .def("init", &ds::drive::DSTorqueManager::init, py::arg("config"))
        .def("set_drive_mode", &ds::drive::DSTorqueManager::set_drive_mode, py::arg("mode"))
        .def("set_regen_mode", &ds::drive::DSTorqueManager::set_regen_mode, py::arg("mode"))
        .def("get_config", &ds::drive::DSTorqueManager::get_config)
        .def("compute_torque_limit", &ds::drive::DSTorqueManager::compute_torque_limit,
             py::arg("enhanced"), py::arg("motor_speed_rpm"), py::arg("dt") = 0.01, py::arg("pack_diagnostics") = nullptr)
        .def("get_diagnostics", &ds::drive::DSTorqueManager::get_diagnostics)
        .def("reset_diagnostics", &ds::drive::DSTorqueManager::reset_diagnostics)
        .def("get_motor_temperature", &ds::drive::DSTorqueManager::get_motor_temperature)
        .def("get_inverter_temperature", &ds::drive::DSTorqueManager::get_inverter_temperature)
        .def("get_status_summary", &ds::drive::DSTorqueManager::get_status_summary)
        .def_static("get_version", &ds::drive::DSTorqueManager::get_version);
}
